### ISSUE TITLE
Compile errors: unresolved identifier, etc.

### ISSUE THREAD

**Issue by transat** [AudioKit/MIDIFileEditAndSync#1]
Should this compile from the get-go?
I'm getting a few errors when I try to compile this on Catalina:

**Use of undeclared type 'MIDIEventList'**
**Use of unresolved identifier 'MIDIEventPacket'**
**Use of unresolved identifier 'MIDIInputPortCreateWithProtocol'**

**Comment by transat** [comment]
Apologies. Updating to Xcode 12 and migrating to AK 5 did the trick.

**Comment by aure** [comment]
If you did anything that can be pushed back to the repository to help others, please create a pull request!  Thanks in advance!

**Comment by transat** [comment]
Will do @aure . Also about to push a WIP upgrade (45 issues remaining) of the ROMPlayer.

**Comment by transat** [comment]
I've sent a PR for this.
